version: "3.8"

services:
  telegrambot:
    image: telegrambot
    container_name: telegrambot
    networks:
      - sensor_network
    depends_on:
      - sensors2rpi
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    sensors2rpi:
      image: sensors2rpi
      container_name: sensors2rpi
      networks:
        - sensor_network
      ports:
        - "8080:8080"
        - "1883:1883"
      restart: unless-stopped

networks:
  sensor_network:
    external: true # verwendet das existierende Netzwerk


# Telegram Bot h채ngt sich an bestehendes sensors2rpi an:
# Falls sensors2rpi bereits l채uft, wird es nicht neu gestartet
# Falls sensors2rpi noch nicht l채uft, wird es automatisch gestartet

# Soll der Bot nur getestet werden, kann er auch mit cargo run lokal ausgef체hrt werden
